{% set name = "nb2plots" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matthew-brett/nb2plots/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1d255c39b8b1d30d0598cf06e3753dd3f77912c2fd0e97ead10ed516732e9f69

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipython[notebook] >=4.0
    - sphinx >=1.4
    - numpy >=1.7.1
    - matplotlib-base >=2.0
    - six >=1.10
    - sphinxtesters >=0.2
    - texext
    - nbconvert

test:
  imports:
    - nb2plots
    - nb2plots.testing
    - nb2plots.tests

about:
  home: http://github.com/matthew-brett/nb2plots
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Converting between ipython notebooks and sphinx docs'

  description: |
    nb2plots converts Jupyter notebooks to ReST files for Sphinx, and back again.
    Nb2plots assumes that the ReST document will become the source for your Sphinx
    web pages, but also for future versions of the notebook. The notebook may
    serve as a draft for the polished ReST page, and an output format from the Sphinx build. 
  doc_url: https://matthew-brett.github.com/nb2plots
  dev_url: http://github.com/matthew-brett/nb2plots

extra:
  recipe-maintainers:
    - CurtLH
