travis:
  secure:
    BINSTAR_TOKEN: n2Foq31uL+Feho3hwoVA6F38TsIeEW9/MJtYEjs482hG3jhrlbJW3idDHOPgBtkiZUzJlvDKpV4L/rc3be2MmPt8pPhmVKENBftcEzy+8ktafb0gGbH/66lQYX0Okdc89wODnYHrizaYT54FT13KBKnPlZZndVfVyNDTyhzJqA9DrB+KNQAFyUOAV0V1UemyIv4jyJmvtEldu6B9VfyIV8TpAVSicpAjaFqNLJtlkD1kZHkf/h0+nweNGUe6LHA9ceGZth769cPPYMTxbtk3BppNp26ypImScSx6Ir801caS1Lm0x5ySn9XlBkYkvR3ClFx3gcNWLrrKgrLGFlGR75NaPeVC1BugnxHzrvOTAHDT/tuCf8kZ5oezgVx2KN31WCrCnO3cFXNGEceOm3nvmBmk8OC3+Pp9cfAJyqZs8ZlSXn5q/vTvFVAHE6/SebpIB2l1AQ//+6xv9fYiVY4BTc6uPPM6dD+2Sm5mQwxzDCgl/1GjAFENaVVIkvomfq9MjPU3qnv4FKkbyIHlZe6lNRWOT6b2nxfSLnFEnQgUvBQHuUYKqArA4MIhpZ+R1+9iuDX7/6IJsFwGVHrHP0cMZL7WRd0iIUKAMd4oY38dEv7rkGi+rieS29pHCtammoFQIrYxuLyote8KyTTWNsrAOnlsHe8zhby9Zji3BQh9JbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
