travis:
  secure:
    BINSTAR_TOKEN: XefFLA2ucpRE/gKeiJs4Dzt8WlMGKIUgPKQs5u7kCRXPwcEIc4b1hDoKLtYWMaHEwHgD91ddSQ2xcp7L1se42zO2I3uhLnhKwWaI4NbHNTKGw1TJDwUkfZvmMFb0HQEQg4N0g70BHSE+v+k2xeOfAbE/5hvubh0UHx37Drqk6WAbNADqkU8EUnOE6LDXM+8rkXnxzJ05pJnpSJOA7R00QWmHgOBawWN5pzXLFVgG1azZpdlx20ft1iGA7pnSxeyGnn1mYCMSRfjhwhoWZk8MTI0Wdu5RFURsjxerww/71BOPSnqK1TZIJ/UdMKi4EUyit8TaFRWn6P1S2zrmV7DH5Jex+WbGzworcG39SNqv+xQh65YdAXt7aA4iyL7Tbu5mRJ6c4/KDVNfIPPw6y/Rpk0e53sgPTbA9p2Lt1KoVsoNxUiSvZu8PTAsa1ulTbIKze6Tg8agb4IvYaAY36SkqGSYVrXq6V5a3g6z4RxV38+n16wQ2VzEcBP6LM8qoJ8qf9fhikHIXWwW+gu8jNHnUTVotFvb7nKXcg6OEoyniX319NapMl/U4PqT+jHnSTOkHweiQ2ZwvS58mDSUQOr/hUMB+2hFaiN77lFX1J3khmW25WKgJ6UuwrVb9Od1AskJg74rFt8mIxXps7SeLzDfqiOSHRfBdKZ43/BIbY3O9wxM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
